plugins {
    id 'nva.data.report.api.java-conventions'
}

dependencies {
    api(nvaCatalog.aws.lambda.core)
    api(nvaCatalog.aws.sdk2.eventbridge)
    api(nvaCatalog.aws.sdk2.s3)
    api(nvaCatalog.jackson.annotations)
    api(nvaCatalog.jackson.core)
    api(nvaCatalog.jackson.databind)
    api(nvaCatalog.jena.arq)
    api(nvaCatalog.jena.core)
    api(nvaLibs.core)
    api(nvaLibs.eventhandlers)
    api(nvaLibs.json)
    implementation(libs.commons.csv)
    implementation(libs.commons.text)
    implementation(nvaCatalog.aws.sdk2.http.client)
    implementation(nvaCatalog.aws.sdk2.sdk.core)
    implementation(nvaCatalog.aws.sdk2.urlconnection)
    implementation(nvaCatalog.log4j.core)
    implementation(nvaCatalog.slf4j.api)
    implementation(nvaLibs.s3)
    runtimeOnly(nvaCatalog.log4j.api)
    runtimeOnly(nvaCatalog.log4j.slf4j.impl)
    testImplementation(libs.commons.io)
    testImplementation(libs.titanium.json.ld)
    testImplementation(nvaCatalog.junit.jupiter.api)
    testImplementation(nvaCatalog.junit.jupiter.params)
    testImplementation(nvaLibs.testutils)
    testImplementation(project(':testing-utils'))
    testRuntimeOnly(libs.jena.fuseki)
}

test {
    environment("QUERY_PATH", "gsp/sparql")
    environment("API_HOST", "example.org")
}
