plugins {
    id 'jacoco-report-aggregation'
    id 'base'
    id 'java-library'
    id 'io.github.michael-nestler.spectral'
}

repositories {
    mavenCentral()
}

dependencies {
    subprojects.forEach {
        jacocoAggregation it
    }
}

reporting {
    reports {
        testCodeCoverageReport(JacocoCoverageReport) {
            testSuiteName = "test"
        }
    }
}

tasks.named('check') {
    dependsOn tasks.named('testCodeCoverageReport', JacocoReport)
}

configurations {
    compile.exclude module: 'testing-utils'
}

spectral {
    documents.from("docs/openapi.yaml")
    ruleset.set(file('.spectral.yaml'))
}