plugins {
    id 'nva.root-module-conventions'
}

nva {
    dependencyAnalysis {
        enforced = true
    }
    // Excluding testing-utils from coverage checks because it is largely unused
    generatedCode = ['no/sikt/nva/data/report/testing/utils/**']
    spectral {
        documents = ['docs/*.yaml']
        rulesetFile = file('.spectral.yaml')
    }
    spotless {
        enabled = true
    }
}
