AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: >
  SAM Template for NVA data report API

Parameters:
  # TODO: Determine access to API
  CognitoAuthorizerArn:
    Type: 'AWS::SSM::Parameter::Value<String>'
    Description: Reference to Cognito UserPool for the stage
    Default: CognitoAuthorizerArn
  ExternalCognitoAuthorizerArn:
    Type: 'AWS::SSM::Parameter::Value<String>'
    Description: Reference to ARN of ExternalUsers UserPool
    Default: ExternalCognitoAuthorizerArn
  CognitoAuthorizationUri:
    Type: 'AWS::SSM::Parameter::Value<String>'
    Default: '/NVA/CognitoUri'
  ProjectName:
    Type: String
    Default: nva-data-report
  ApiDomain:
    Type: 'AWS::SSM::Parameter::Value<String>'
    Description: The Api domain
    Default: /NVA/ApiDomain
  CustomDomainBasePath:
    Type: String
    Description: Base path mapping
    Default: report
  Suffix:
    Type: String
    Default: ''
    Description: Suffix used for naming resources for feature branches to avoid conflicts.
  ResourcesBucket:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /NVA/Events/PersistedEntriesBucketName
  ResourcesPrefix:
    Type: String
    Description: Prefix for resource files in persisted-resources bucket
    Default: resources/
  NviCandidatesPrefix:
    Type: String
    Description: Prefix for nvi-candidate files in persisted-resources bucket
    Default: nvi-candidates/
  LoaderBucketName:
    Type: 'String'
    Default: "loader-input-files"
    Description: Name of bucket for input NQuads files
  KeyBatchesBucketName:
    Type: 'String'
    Default: "data-report-key-batches"
    Description: Name of bucket for key batch files
  NviReportsBucketName:
    Type: 'String'
    Default: "nvi-reports"
    Description: Name of bucket for nvi reports
  ExportBucketName:
    Type: 'String'
    Default: "data-report-csv-export"
    Description: Name of bucket for csv export files
  SlackSnsArn:
    Type: AWS::SSM::Parameter::Value<String>
    Default: '/NVA/Monitoring/SlackSnsArn'
  AllowedOrigins:
    Type: String
    Description: comma separated list of external clients that are allowed to contact the HTTP APIs, "*" indicates that all origins are allowed
    Default: '*'

Conditions:
  WithSuffix: !Not [ !Equals [ !Ref Suffix, '' ] ]

Globals:
  Function:
    Runtime: java21
    MemorySize: 1536
    Environment:
      Variables:
        API_HOST: !Ref ApiDomain

Resources:

  # ---- SQS ----
  GenerateNviInstitutionReportQueue:
    Type: AWS::SQS::Queue
    Properties:
      VisibilityTimeout: 600
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt GenerateNviInstitutionReportDLQ.Arn
        maxReceiveCount: 5
      # ---- DLQs ----
  GenerateNviInstitutionReportDLQ:
    Type: AWS::SQS::Queue
    Properties:
      MessageRetentionPeriod: 1209600 #14 days
  DataReportPersistedResourceDLQ:
    Type: AWS::SQS::Queue
    Properties:
      MessageRetentionPeriod: 1209600 #14 days
  DataLoadingDLQ:
    Type: AWS::SQS::Queue
    Properties:
      MessageRetentionPeriod: 1209600 #14 days

  # ---- Logging ----

  ApiAccessLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/aws/lambda/${FetchDataReportHandler}'
      RetentionInDays: 5

  DataLoadingLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/aws/lambda/${DataLoadingHandler}'
      RetentionInDays: 5

  # ---- Policies ----

  SecretsManagerPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - secretsmanager:GetSecretValue
            Resource:
              - !Sub "arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:BackendCognitoClientCredentials-*"

  DeleteS3ObjectPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - 's3:DeleteObject'
            Resource:
              - !GetAtt KeyBatchesBucket.Arn

  S3ManagedPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - s3:Get*
              - s3:List*
              - s3:PutObject
              - events:*
            Resource: '*'

  S3NviReportsManagedPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - s3:Get*
              - s3:List*
              - s3:PutObject
            Resource: !Sub '${NviReportsBucket.Arn}/*'

  SqsManagedPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - sqs:ReceiveMessage
              - sqs:DeleteMessage
              - sqs:SendMessage
              - sqs:GetQueueAttributes
            Resource:
              - !GetAtt DataLoadingDLQ.Arn
              - !GetAtt GenerateNviInstitutionReportQueue.Arn
              - !GetAtt GenerateNviInstitutionReportDLQ.Arn
  DeployToVpnPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - ec2:DescribeNetworkInterfaces
              - ec2:CreateNetworkInterface
              - ec2:DeleteNetworkInterface
              - ec2:DescribeInstances
              - ec2:AttachNetworkInterface
            Resource: '*'

  InvokeLambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !GetAtt DataLoadingHandler.Arn
      Action: 'lambda:InvokeFunction'
      Principal: 'events.amazonaws.com'
      SourceArn: !GetAtt PersistedResourcesEventRule.Arn

  #============================= Roles ==========================================================
  DataReportApi:
    Type: AWS::Serverless::Api
    Properties:
      AccessLogSetting:
        DestinationArn: !GetAtt ApiAccessLogGroup.Arn
        Format: '{ "apiId": "$context.apiId", "requestId": "$context.requestId", "requestTime": "$context.requestTime", "requestTimeEpoch": "$context.requestTimeEpoch", "httpMethod": "$context.httpMethod", "path": "$context.path", "status": "$context.status",  "error.message": "$context.error.message" }'
      StageName: Prod
      EndpointConfiguration:
        Type: REGIONAL
      DefinitionBody:
        'Fn::Transform':
          Name: AWS::Include
          Parameters:
            Location: ./docs/openapi.yaml
      BinaryMediaTypes:
        - application/vnd.ms-excel
        - application/vnd.openxmlformats-officedocument.spreadsheetml.sheet

  ApiPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref FetchDataReportHandler
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${DataReportApi}/prod/GET/report"

  #===========================BasePathMappings========================================================
  BasePathMapping:
    Type: AWS::ApiGateway::BasePathMapping
    Properties:
      BasePath: !If
        - WithSuffix
        - !Sub ${CustomDomainBasePath}-${Suffix}
        - !Sub ${CustomDomainBasePath}
      DomainName: !Ref ApiDomain
      RestApiId: !Ref DataReportApi
      Stage: !Ref DataReportApi.Stage

  #===========================EventBridge Rule========================================================
  PersistedResourcesEventRule:
    Type: AWS::Events::Rule
    Properties:
      Description: "Trigger on create and delete events for S3 bucket persisted-resources"
      EventPattern:
        source:
          - "aws.s3"
        detail-type:
          - "Object Created"
        detail:
          bucket:
            name:
              - !Ref ResourcesBucket
          object:
            key:
              - prefix: !Ref ResourcesPrefix
              - prefix: !Ref NviCandidatesPrefix
      State: ENABLED
      Targets:
        - Arn: !GetAtt DataLoadingHandler.Arn
          Id: "DataLoadingHandler"
          InputTransformer:
            InputPathsMap:
              bucketName: "$.detail.bucket.name"
              key: "$.detail.object.key"
              eventType: "$.detail.reason"
            InputTemplate: '{"bucketName": <bucketName>, "key": <key>, "eventType": <eventType>}'
          DeadLetterConfig:
            Arn: !GetAtt DataReportPersistedResourceDLQ.Arn
          RetryPolicy:
            MaximumRetryAttempts: 3

  # ---- Handler ----
  FetchDataReportHandler:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: report-api
      Handler: no.sikt.nva.data.report.api.fetch.FetchDataReport::handleRequest
      Timeout: 600
      MemorySize: 1536
      AutoPublishAlias: live
      Environment:
        Variables:
          ALLOWED_ORIGIN: !Ref AllowedOrigins
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /{type}
            Method: get
            RestApiId: !Ref DataReportApi

  NviInstitutionReportGenerator:
    Type: AWS::Serverless::Function
    Properties:
      Handler: no.sikt.nva.data.report.api.fetch.NviInstitutionReportGenerator::handleRequest
      CodeUri: report-api
      Timeout: 600
      MemorySize: 1536
      AutoPublishAlias: live
      Environment:
        Variables:
          ALLOWED_ORIGIN: !Ref AllowedOrigins
          NVI_REPORTS_BUCKET: !Ref NviReportsBucket
          GRAPH_DATABASE_PAGE_SIZE: 500
      Events:
        SqsEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt GenerateNviInstitutionReportQueue.Arn
            BatchSize: 1
            #Note: NviInstitutionReportGenerator is implemented to handle only batch size 1.
            #Don't change the batch size value, unless you change the implementation.
      EventInvokeConfig:
        DestinationConfig:
          OnFailure:
            Type: SQS
            Destination: !GetAtt GenerateNviInstitutionReportDLQ.Arn

  FetchNviInstitutionReportPresignerHandler:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: report-api
      Handler: no.sikt.nva.data.report.api.fetch.FetchNviInstitutionReportPresigner::handleRequest
      Policies:
        - !GetAtt SecretsManagerPolicy.PolicyArn
        - !GetAtt SqsManagedPolicy.PolicyArn
        - !GetAtt S3NviReportsManagedPolicy.PolicyArn
      Timeout: 600
      MemorySize: 1536
      AutoPublishAlias: live
      Environment:
        Variables:
          ALLOWED_ORIGIN: !Ref AllowedOrigins
          COGNITO_HOST: !Ref CognitoAuthorizationUri
          BACKEND_CLIENT_SECRET_NAME: 'BackendCognitoClientCredentials'
          NVI_REPORTS_BUCKET: !Ref NviReportsBucket
          REPORT_QUEUE_URL: !Ref GenerateNviInstitutionReportQueue
          SIGN_DURATION_IN_MINUTES: 60
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /institution/nvi-approval/{reportingYear}
            Method: get
            RestApiId: !Ref DataReportApi

  DataLoadingHandler:
    Type: AWS::Serverless::Function
    Properties:
      Handler: no.sikt.nva.data.report.api.etl.SingleObjectDataLoader::handleRequest
      CodeUri: data-loading
      Policies:
        - !GetAtt S3ManagedPolicy.PolicyArn
        - !GetAtt SqsManagedPolicy.PolicyArn
        - !GetAtt DeployToVpnPolicy.PolicyArn
      Timeout: 600
      MemorySize: 1536
      AutoPublishAlias: live
      Environment:
        Variables:
          BACKEND_CLIENT_AUTH_URL: !Ref CognitoAuthorizationUri
          BACKEND_CLIENT_SECRET_NAME: 'BackendCognitoClientCredentials'
          EXPANDED_RESOURCES_BUCKET: !Ref ResourcesBucket
          EXPORT_BUCKET: !Ref ExportBucket
      EventInvokeConfig:
        DestinationConfig:
          OnFailure:
            Type: SQS
            Destination: !GetAtt DataLoadingDLQ.Arn


  ResetDatabaseButton:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: database-tools
      Handler: no.sikt.nva.data.report.dbtools.DatabaseResetHandler::handleRequest
      VpcConfig:
        SecurityGroupIds:
          - !Ref LambdaSecurityGroup
        SubnetIds:
          - !Ref LambdaSubnet1
          - !Ref LambdaSubnet2
      Policies:
        - !GetAtt NeptuneManagedPolicy.PolicyArn
        - !GetAtt DeployToVpnPolicy.PolicyArn
      Timeout: 600
      MemorySize: 1536
      AutoPublishAlias: live

  #---- Generates key batches in bucket ----

  GenerateKeyBatchesHandler:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: bulk-load
      Handler: no.sikt.nva.data.report.api.etl.transformer.GenerateKeyBatchesHandler::handleRequest
      Policies:
        - !GetAtt S3ManagedPolicy.PolicyArn
      Timeout: 600
      MemorySize: 1536
      AutoPublishAlias: live
      Environment:
        Variables:
          EVENT_BUS: !GetAtt BatchLoadEventBus.Name
          EXPANDED_RESOURCES_BUCKET: !Ref ResourcesBucket
          KEY_BATCHES_BUCKET: !Ref KeyBatchesBucket
          TOPIC: 'ReportApi.Bulk.KeyBasedBatch'
      Events:
        BatchIndexEvent:
          Type: EventBridgeRule
          Properties:
            EventBusName: !GetAtt BatchLoadEventBus.Name
            Pattern:
              detail:
                topic: [ 'ReportApi.Bulk.KeyBasedBatch' ]

  NquadsBulkTransformerHandler:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: bulk-load
      Handler: no.sikt.nva.data.report.api.etl.transformer.NquadsTransformer::handleRequest
      Timeout: 600
      MemorySize: 1536
      AutoPublishAlias: live
      Policies:
        - !GetAtt S3ManagedPolicy.PolicyArn
        - !GetAtt DeleteS3ObjectPolicy.PolicyArn
      Environment:
        Variables:
          EVENT_BUS: !GetAtt BatchLoadEventBus.Name
          EXPANDED_RESOURCES_BUCKET: !Ref ResourcesBucket
          KEY_BATCHES_BUCKET: !Ref KeyBatchesBucket
          LOADER_BUCKET: !Ref LoaderBucket
          TOPIC: 'ReportApi.Bulk.TransformKeyBatchNquads'
          API_HOST: !Ref ApiDomain
      Events:
        BatchIndexEvent:
          Type: EventBridgeRule
          Properties:
            EventBusName: !GetAtt BatchLoadEventBus.Name
            Pattern:
              detail:
                topic: [ 'ReportApi.Bulk.TransformKeyBatchNquads' ]

  CsvBulkTransformerHandler:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: bulk-export
      Handler: no.sikt.nva.data.report.api.export.CsvTransformer::handleRequest
      Timeout: 600
      MemorySize: 1536
      AutoPublishAlias: live
      Policies:
        - !GetAtt S3ManagedPolicy.PolicyArn
      Environment:
        Variables:
          EVENT_BUS: !GetAtt BatchLoadEventBus.Name
          EXPANDED_RESOURCES_BUCKET: !Ref ResourcesBucket
          KEY_BATCHES_BUCKET: !Ref KeyBatchesBucket
          EXPORT_BUCKET: !Ref ExportBucket
          TOPIC: 'ReportApi.Bulk.TransformKeyBatchCsv'
      Events:
        BatchIndexEvent:
          Type: EventBridgeRule
          Properties:
            EventBusName: !GetAtt BatchLoadEventBus.Name
            Pattern:
              detail:
                topic: [ 'ReportApi.Bulk.TransformKeyBatchCsv' ]

  #---- EventBus ----

  BatchLoadEventBus:
    Type: AWS::Events::EventBus
    Properties:
      Name: !If
        - WithSuffix
        - !Join [ "-",[ "BatchLoadEventBus", !Ref Suffix ] ]
        - "BatchLoadEventBus"

  #---- Buckets ----
  LoaderBucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: Private
      BucketName: !Sub "${LoaderBucketName}-${AWS::AccountId}"
      LifecycleConfiguration:
        Rules:
          - Id: DeleteContentAfter3Days
            Status: Enabled
            ExpirationInDays: 3

  KeyBatchesBucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: Private
      BucketName: !Sub "${KeyBatchesBucketName}-${AWS::AccountId}"
      LifecycleConfiguration:
        Rules:
          - Id: DeleteContentAfter3Days
            Status: Enabled
            ExpirationInDays: 3

  ExportBucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: Private
      BucketName: !Sub "${ExportBucketName}-${AWS::AccountId}"

  NviReportsBucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: Private
      BucketName: !Sub "${NviReportsBucketName}-${AWS::AccountId}"
      LifecycleConfiguration:
        Rules:
          - Id: DeleteContentAfter3Days
            Status: Enabled
            ExpirationInDays: 3


  #============================= Alarms =========================================================

  NviInstitutionReportDLQAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: report-api-nvi-institution-report-dlq-alarm
      MetricName: ApproximateNumberOfMessagesVisible
      Namespace: AWS/SQS
      Statistic: Sum
      Dimensions:
        - Name: QueueName
          Value: !GetAtt GenerateNviInstitutionReportDLQ.QueueName
      Period: 300
      EvaluationPeriods: 1
      Threshold: 1
      ComparisonOperator: GreaterThanOrEqualToThreshold
      AlarmActions:
        - !Ref SlackSnsArn
