PREFIX : <https://nva.sikt.no/ontology/publication#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT DISTINCT
  ?publicationId
  ?status
  ?publicationIdentifier
  ?contributorIdentifier
  ?contributorName
  ?contributorSequenceNumber
  ?contributorRole
  WHERE {
      ?uri a :Publication ;
           :status ?publicationStatus ;
           :modifiedDate ?modifiedDate ;
           :identifier ?publicationIdentifier .

      BIND(REPLACE(STR(?publicationStatus), "https://nva.sikt.no/ontology/publication#", "", "i") AS ?status)

      ?uri :entityDescription/:contributor ?contributor .
      BIND(STR(?uri) AS ?publicationId)

      ?contributor :identity ?personId ;
                   :role ?roleRaw ;
                   :sequence ?contributorSequenceNumber .
      ?personId :name ?contributorName .
      BIND(REPLACE(STR(?personId), "^.*/([^/]*)$", "$1") AS ?contributorIdentifier)
      ?roleRaw a ?roleType
      FILTER(!ISBLANK(?personId))
      BIND(REPLACE(STR(?roleType), "https://nva.sikt.no/ontology/publication#", "", "i") AS ?contributorRole)
}