PREFIX : <https://nva.sikt.no/ontology/publication#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
SELECT DISTINCT
  ?publicationId
  ?contributorIdentifier
  ?affiliationId
  ?institutionId
  ?institutionPoints
  ?pointsForAffiliation
  ?institutionApprovalStatus
  ?globalApprovalStatus
  ?reportedPeriod
  ?totalPoints
  ?publicationTypeChannelLevelPoints
  ?authorShareCount
  ?internationalCollaborationFactor
  ?isApplicable
WHERE {
    {
      ?candidate a :NviCandidate ;
        :modifiedDate ?modifiedDate ;
        :publicationDetails ?publicationUri ;
        :isApplicable ?isApplicableBoolean ;
        :points ?totalPoints ;
        :globalApprovalStatus ?globalApprovalStatus ;
        :internationalCollaborationFactor ?internationalCollaborationFactor ;
        :creatorShareCount ?authorShareCount ;
        :publicationTypeChannelLevelPoints ?publicationTypeChannelLevelPoints .

      OPTIONAL {
        ?candidate :reported ?reported ;
                   :reportingPeriod ?reportingPeriod .
        ?reportingPeriod a :ReportingPeriod ;
                         :year ?reportedYear .
        BIND(IF(?reported = true, ?reportedYear, "NotReported") AS ?reportedPeriod)
      }

      BIND(STR(?publicationUri) AS ?publicationId)
      BIND(STR(?isApplicableBoolean) AS ?isApplicable)

      ?publicationUri :contributor ?contributorId .
      ?contributorId a :NviContributor .
      BIND(STR(?contributorId) AS ?contributorIdString)
      BIND(REPLACE(STR(?contributorId), "^.*/([^/]*)$", "$1") AS ?contributorIdentifier)

      ?contributorId :affiliation ?affiliationUri .
      ?affiliationUri a ?NviOrganization .
      BIND(STR(?affiliationUri) AS ?affiliationId)

      ?candidate :approval ?approval .
      ?approval a :Approval ;
        :approvalStatus ?institutionApprovalStatus ;
        :points ?institutionPointsNode ;
        :institutionId ?organizationUri ;
        :involvedOrganization ?affiliationId .

      BIND(STR(?organizationUri) AS ?institutionId)

      ?institutionPointsNode a :InstitutionPoints ;
        :institutionPoints ?institutionPoints ;
        :creatorAffiliationPoints ?creatorAffiliationPoints .

      ?creatorAffiliationPoints a :CreatorAffiliationPoints ;
        :nviCreator ?contributorIdString ;
        :affiliationId ?affiliationId ;
        :points ?pointsForAffiliation .
    }
    UNION
    {
      ?candidate a :NviCandidate ;
        :modifiedDate ?modifiedDate ;
        :publicationDetails ?publicationUri ;
        :isApplicable ?isApplicableBoolean .

      BIND(STR(?publicationUri) AS ?publicationId)
      BIND(STR(?isApplicableBoolean) AS ?isApplicable)

      FILTER(?isApplicableBoolean = false)

    }
}