PREFIX : <https://nva.sikt.no/ontology/publication#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT DISTINCT
    ?publicationId
    ?publicationIdentifier
    ?source
    ?identifier
WHERE {
    ?uri a :Publication ;
                    :modifiedDate ?modifiedDate ;
                    :identifier ?publicationIdentifier ;
                    :funding ?funding .
    BIND(STR(?uri) AS ?publicationId)
    ?funding :identifier ?identifier ;
             :source ?sourceId .
    ?sourceId :identifier ?source .
    FILTER(?modifiedDate >= "__AFTER__"^^xsd:dateTime)
    FILTER(?modifiedDate < "__BEFORE__"^^xsd:dateTime)
} ORDER BY ?publicationId LIMIT __PAGE_SIZE__ OFFSET __OFFSET__