PREFIX : <https://nva.sikt.no/ontology/publication#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT DISTINCT
    ?publicationId
    ?status
    ?publicationIdentifier
    ?fundingSource
    ?fundingId
WHERE {
  GRAPH ?g {
    ?uri a :Publication ;
                    :status ?publicationStatus ;
                    :modifiedDate ?modifiedDate ;
                    :identifier ?publicationIdentifier ;
                    :funding ?funding .

    FILTER(?modifiedDate >= "__AFTER__"^^xsd:dateTime)
    FILTER(?modifiedDate < "__BEFORE__"^^xsd:dateTime)

    BIND(STR(?uri) AS ?publicationId)
    BIND(REPLACE(STR(?publicationStatus), "^.*/([^/]*)$", "$1") AS ?status)

    ?funding :identifier ?fundingId ;
             :source ?sourceId .
    ?sourceId :identifier ?fundingSource .
  }
} LIMIT __PAGE_SIZE__ OFFSET __OFFSET__