PREFIX : <https://nva.sikt.no/ontology/publication#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

SELECT DISTINCT
  ?ARSTALL
  ?VARBEIDLOPENR
  ?ARSTALL_REG
  ?STATUS_KONTROLLERT
  ?PUBLIKASJONSFORM
  ?PUBLISERINGSKANALTYPE
  ?ISSN
  ?KVALITETSNIVAKODE
  ?PERSONLOPENR
  ?INSTITUSJONSNR
  ?AVDNR
  ?UNDAVDNR
  ?GRUPPENR
  ?ETTERNAVN
  ?FORNAVN
  ?PUBLISERINGSKANALNAVN
  ?VA_TITTEL
  ?RAPPORTSTATUS
  ?VEKTINGSTALL
  ?FAKTORTALL_SAMARBEID
  ?FORFATTERVEKT
  WHERE {
   GRAPH ?nvi {
       ?candidate a :NviCandidate ;
               :publicationDetails ?publicationUri ;
               :isApplicable true ;
               :internationalCollaborationFactor ?FAKTORTALL_SAMARBEID ;
               :globalApprovalStatus ?RAPPORTSTATUS ;
               :publicationTypeChannelLevelPoints ?VEKTINGSTALL ;
               :reportingPeriod ?reportingPeriod .

       ?reportingPeriod a :ReportingPeriod ;
                        :year "__REPLACE_WITH_REPORTING_YEAR__" .
       BIND("__REPLACE_WITH_REPORTING_YEAR__" AS ?ARSTALL)

       BIND(?publicationUri AS ?VARBEIDLOPENR)

       ?publicationUri :contributor ?contributorId .
       ?contributorId a :NviContributor .
       BIND(?contributorId AS ?PERSONLOPENR)

       ?contributorId :affiliation ?affiliationUri .
       ?affiliationUri a ?NviOrganization .

       BIND(URI("__REPLACE_WITH_TOP_LEVEL_ORGANIZATION__") AS ?organizationUri)
       BIND(STR(?affiliationUri) AS ?affiliationUriString)

       ?candidate :approval ?approval .
       ?approval a :Approval ;
         :approvalStatus ?STATUS_KONTROLLERT ;
         :points ?institutionPoints ;
         :institutionId ?organizationUri ;
         :involvedOrganization ?affiliationUriString .

       ?institutionPoints a :InstitutionPoints ;
         :creatorAffiliationPoints ?creatorAffiliationPoints .

       ?creatorAffiliationPoints a :CreatorAffiliationPoints ;
         :nviCreator ?contributorIdString ;
         :affiliationId ?affiliationId ;
         :points ?FORFATTERVEKT .

       BIND(?affiliationUri AS ?GRUPPENR)
       BIND(?affiliationUri AS ?INSTITUSJONSNR)
       BIND(?affiliationUri AS ?AVDNR)
       BIND(?affiliationUri AS ?UNDAVDNR)

     }
     GRAPH ?nva {
        ?publicationUri a :Publication ;
             :identifier ?publicationIdentifier ;
             :entityDescription ?entityDescription ;
             :entityDescription/:contributor ?contributor .

        ?entityDescription :publicationDate ?publicationDate .
        ?entityDescription :mainTitle ?VA_TITTEL .
        ?entityDescription :reference ?reference .
        ?reference :publicationContext ?publicationContext .
        ?publicationContext a ?PUBLISERINGSKANALTYPE ;
                            :name ?PUBLISERINGSKANALNAVN ;
                            :scientificValue ?KVALITETSNIVAKODE .

        ?publicationDate :year ?ARSTALL_REG .
        ?reference :publicationInstance ?instance .
        ?instance a ?PUBLIKASJONSFORM .

        OPTIONAL {
            ?publicationContext :printIssn ?ISSN
        }

        ?contributor :identity ?contributorId .
        ?contributorId :name ?contributorName .
        BIND(?contributorName AS ?ETTERNAVN)
        BIND(?contributorName AS ?FORNAVN)
     }
    } LIMIT __PAGE_SIZE__ OFFSET __OFFSET__
    ##LIMIT 10000 #TODO: Handle cases where the limit is reached


