PREFIX : <https://nva.sikt.no/ontology/publication#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT DISTINCT
  ?publicationId
  ?contributorIdentifier
  ?affiliationId
  ?institutionId
  ?institutionPoints
  ?institutionApprovalStatus
  WHERE {
    GRAPH ?g {
      ?publicationUri a :PublicationDetails .
      BIND(STR(?publicationUri) AS ?publicationId) .

      ?publicationUri :contributor ?contributorUri .
      #TODO: Check contributor type
      #TODO: Check contributor is nviContributor
      BIND(REPLACE(STR(?contributorUri), "^.*/([^/]*)$", "$1") AS ?contributorIdentifier)

      ?contributorUri :affiliation ?affiliationUri .
      #TODO: Check affiliation is nviAffiliation
      BIND(REPLACE(STR(?affiliationUri), "^.*/([^/]*)$", "$1") AS ?affiliationId)
  }
} LIMIT __PAGE_SIZE__