PREFIX : <https://nva.sikt.no/ontology/publication#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT DISTINCT
  ?publicationId
  ?contributorIdentifier
  ?affiliationId
  ?institutionId
  ?institutionPoints
  ?institutionApprovalStatus
  WHERE {
    GRAPH ?g {
      ?candidate a :NviCandidate ;
        :modifiedDate ?modifiedDate ;
        :publicationDetails ?publicationId .

      ?publicationId :contributor ?contributorUri .
      ?contributorUri :isNviContributor ?isNviContributor .
      FILTER(?isNviContributor = true)
      BIND(REPLACE(STR(?contributorUri), "^.*/([^/]*)$", "$1") AS ?contributorIdentifier)

      ?contributorUri :affiliation ?affiliationUri .
      ?affiliationUri :isNviAffiliation ?isNviAffiliation .
      FILTER(?isNviAffiliation = true)
      BIND(REPLACE(STR(?affiliationUri), "^.*/([^/]*)$", "$1") AS ?affiliationId)

      FILTER(?modifiedDate >= "__AFTER__"^^xsd:dateTime)
      FILTER(?modifiedDate < "__BEFORE__"^^xsd:dateTime)
  }
} LIMIT __PAGE_SIZE__