PREFIX : <https://nva.sikt.no/ontology/publication#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT DISTINCT
    ?publicationId
    ?publicationTitle
    ?publicationCategory
    ?publicationDate
    ?channelType
    ?channelIdentifier
    ?channelName
    ?channelOnlineIssn
    ?channelPrintIssn
    ?channelLevel
    ?publicationIdentifier
WHERE {
  GRAPH ?g {
    ?uri a :Publication ;
         :modifiedDate ?modifiedDate ;
         :identifier ?publicationIdentifier ;
         :entityDescription ?entityDescription .
    BIND(STR(?uri) AS ?publicationId)

    ?entityDescription :mainTitle ?publicationTitle ;
                       :publicationDate ?date .
    ?date :year ?year ;

    OPTIONAL {
        ?date :month ?month .
    }
    OPTIONAL {
        ?date :day ?day .
    }

    BIND(IF(BOUND(?month), CONCAT("-", ?month), "") AS ?monthPart)
    BIND(IF(BOUND(?day), CONCAT("-", ?day), "") AS ?dayPart)
    BIND(CONCAT(?year, CONCAT(?monthPart, ?dayPart)) AS ?publicationDate)

    ?entityDescription :reference ?reference .
    ?reference :publicationContext ?publicationContext .
    ?publicationContext a ?channelTypeId ;
                        :name ?channelName ;
                        :scientificValue ?channelLevel .

    BIND(REPLACE(STR(?publicationContext), "^.*/([^/]+)/[^/]+$", "$1") AS ?channelIdentifier)
    BIND(STR(?channelTypeId) AS ?channelType)
    ?reference :publicationInstance ?instance .
    ?instance a ?instanceType .
    BIND(REPLACE(STR(?instanceType), "https://nva.sikt.no/ontology/publication#", "", "i") AS ?publicationCategory)

    OPTIONAL {
        ?publicationContext :onlineIssn ?channelOnlineIssn
    }
    OPTIONAL {
        ?publicationContext :printIssn ?channelPrintIssn
    }
    FILTER(?modifiedDate >= "__AFTER__"^^xsd:dateTime)
    FILTER(?modifiedDate < "__BEFORE__"^^xsd:dateTime)
  }
} LIMIT __PAGE_SIZE__ OFFSET __OFFSET__