[versions]
junit = { strictly = '5.10.1' }
nva = { strictly = '1.35.0' }
zalando = { strictly = '0.27.1' }
awsLambdaJavaCore = { strictly = '1.2.2' }
awsLambdaEvents = { strictly = '3.11.2' }
log4j = { strictly = '2.18.0' }
slf4j = { strictly = '2.0.9' }
awslog4j2 = { strictly = '1.5.1' }
awsSdk2 = { strictly = '2.20.141' }
jena = { strictly = '4.7.0' }


[libraries]
junit-jupiter-api = { group = 'org.junit.jupiter', name = 'junit-jupiter-api', version.ref = 'junit' }
junit-jupiter-params = { group = 'org.junit.jupiter', name = 'junit-jupiter-params', version.ref = 'junit' }
junit-jupiter-engine = { group = 'org.junit.jupiter', name = 'junit-jupiter-engine', version.ref = 'junit' }

nva-testutils = { group = 'com.github.bibsysdev', name = 'nvatestutils', version.ref = 'nva' }
nva-logutils = { group = 'com.github.bibsysdev', name = 'logutils', version.ref = 'nva' }

nva-s3 = { group = 'com.github.bibsysdev', name = 's3', version.ref = 'nva' }
nva-json = { group = 'com.github.bibsysdev', name = 'json', version.ref = 'nva' }
nva-commons-core = { group = 'com.github.bibsysdev', name = 'core', version.ref = 'nva' }
nva-commons-auth = { group = 'com.github.bibsysdev', name = 'auth', version.ref = 'nva' }
nva-commons-apigateway = { group = 'com.github.bibsysdev', name = 'apigateway', version.ref = 'nva' }
nva-eventhandlers = { group = 'com.github.bibsysdev', name = 'eventhandlers', version.ref = 'nva' }

aws-sdk2-eventbridge = { group = 'software.amazon.awssdk', name = 'eventbridge', version.ref = 'awsSdk2' }
aws-sdk2-urlconnectionclient = { group = 'software.amazon.awssdk', name = 'url-connection-client', version.ref = 'awsSdk2' }
aws-sdk2-s3 = { group = 'software.amazon.awssdk', name = 's3', version.ref = 'awsSdk2' }
aws-sdk2-core = { group = 'software.amazon.awssdk', name = 'sdk-core', version.ref = 'awsSdk2' }
aws-sdk2-urlconnection = { group = 'software.amazon.awssdk', name = 'url-connection-client', version.ref = 'awsSdk2' }
aws-sdk2-httpClientApi = { group = 'software.amazon.awssdk', name = 'http-client-spi', version.ref = 'awsSdk2' }

aws-lambda-java-core = { group = 'com.amazonaws', name = 'aws-lambda-java-core', version.ref = 'awsLambdaJavaCore' }
aws-lambda-events = { group = 'com.amazonaws', name = 'aws-lambda-java-events', version.ref = 'awsLambdaEvents' }
aws-lambda-log4j2 = { group = 'com.amazonaws', name = 'aws-lambda-java-log4j2', version.ref = 'awslog4j2' }

log4j-core = { group = 'org.apache.logging.log4j', name = 'log4j-core', version.ref = 'log4j' }
log4j-api = { group = 'org.apache.logging.log4j', name = 'log4j-api', version.ref = 'log4j' }
log4j-slf4j18-impl = { group = 'org.apache.logging.log4j', name = 'log4j-slf4j18-impl', version.ref = 'log4j' }
slf4j-api = { group = 'org.slf4j', name = 'slf4j-api', version.ref = 'slf4j' }

jena-core = { group = 'org.apache.jena', name = 'jena-core', version.ref = 'jena' }
jena-arq = { group = 'org.apache.jena', name = 'jena-arq', version.ref = 'jena' }

zalando = { group = 'org.zalando', name = 'problem', version.ref = 'zalando' }


[bundles]
jena = ['jena-core', 'jena-arq']