plugins {
    id 'nva.data.report.api.java-conventions'
}

dependencies {
    api(nvaCatalog.aws.lambda.core)
    api(nvaCatalog.aws.sdk2.eventbridge)
    api(nvaCatalog.aws.sdk2.s3)
    api(nvaCatalog.jackson.annotations)
    api(nvaCatalog.jackson.databind)
    api(nvaLibs.eventhandlers)
    api(nvaLibs.json)
    api(project(':data-report-commons'))
    implementation(nvaCatalog.aws.sdk2.http.client)
    implementation(nvaCatalog.aws.sdk2.sdk.core)
    implementation(nvaCatalog.aws.sdk2.urlconnection)
    implementation(nvaCatalog.jena.arq)
    implementation(nvaCatalog.jena.core)
    implementation(nvaCatalog.log4j.core)
    implementation(nvaCatalog.slf4j.api)
    implementation(nvaLibs.core)
    implementation(nvaLibs.s3)
    runtimeOnly(nvaCatalog.jackson.core)
    runtimeOnly(nvaCatalog.log4j.api)
    runtimeOnly(nvaCatalog.log4j.slf4j.impl)
    testImplementation(nvaCatalog.jackson.core)
    testImplementation(nvaCatalog.junit.jupiter.api)
    testImplementation(nvaCatalog.junit.jupiter.params)
    testImplementation(nvaCatalog.mockito.core)
    testImplementation(nvaLibs.identifiers)
    testImplementation(nvaLibs.testutils)
    testImplementation(project(':testing-utils'))
    testRuntimeOnly(nvaCatalog.junit.jupiter.engine)
}

test {
    environment("API_HOST", "example.org")
    environment("AWS_REGION", "eu-west-1")
    environment("EXPANDED_RESOURCES_BUCKET", "s3://persistedResources")
    environment("KEY_BATCHES_BUCKET", "s3://keyBatches")
    environment("EXPORT_BUCKET", "s3://exportBucket")
    environment("EVENT_BUS", "eventBus")
    environment("TOPIC", "some topic")
}
