PREFIX : <https://nva.sikt.no/ontology/publication#>

CONSTRUCT {
  ?uri a :NviCandidate .
  ?uri :identifier ?identifier .
  ?uri :isApplicable ?isApplicable .
  ?uri :internationalCollaborationFactor ?internationalCollaborationFactor .
  ?uri :globalApprovalStatus ?globalApprovalStatus .
  ?uri :publicationTypeChannelLevelPoints ?publicationTypeChannelLevelPoints .
  ?uri :reportingYear ?reportingYear .
  ?uri :reported ?reported .
  ?uri :publicationId ?publicationId .
  ?uri :nviContributor ?nviContributor .
  ?uri :approval ?approval .

  ?nviContributor :nviAffiliation ?nviAffiliation .

  ?approval :institutionId ?institutionId .
  ?approval :approvalStatus ?approvalStatus .
  ?approval :institutionPoints ?institutionPoints .
  ?approval :creatorAffiliationPoints ?creatorAffiliationPoints .

  ?creatorAffiliationPoints :creator ?creator .
  ?creatorAffiliationPoints :affiliation ?affiliation .
  ?creatorAffiliationPoints :points ?points .

} WHERE {
  ?uri :identifier ?identifier .
  ?uri :isApplicable ?isApplicable .
  ?uri :internationalCollaborationFactor ?internationalCollaborationFactor .
  ?uri :globalApprovalStatus ?globalApprovalStatus .
  ?uri :publicationTypeChannelLevelPoints ?publicationTypeChannelLevelPoints .
  ?uri :reportingPeriod ?reportingPeriod .
  ?uri :reported ?reported .
  ?uri :publicationDetails ?publicationId .
  ?uri :approval ?approval .

  ?reportingPeriod :year ?reportingYear .

  ?publicationId :contributor ?nviContributor .

  ?nviContributor a :NviContributor .
  ?nviContributor :affiliation ?nviAffiliation .
  ?nviAffiliation a :NviOrganization .

  ?approval a :Approval .
  ?approval :institutionId ?institutionId .
  ?approval :approvalStatus ?approvalStatus .
  ?approval :points ?points .

  ?points :creatorAffiliationPoints ?creatorAffiliationPoints .
  ?points :institutionPoints ?institutionPoints .

  ?creatorAffiliationPoints :nviCreator ?creator .
  ?creatorAffiliationPoints :affiliationId ?affiliation .
  ?creatorAffiliationPoints :points ?creator .

}