plugins {
    id 'nva.data.report.api.java-conventions'
}

dependencies {
    api(nvaCatalog.aws.lambda.core)
    api(nvaCatalog.aws.lambda.events)
    api(nvaCatalog.aws.sdk2.s3)
    api(nvaCatalog.slf4j.api)
    api(nvaLibs.core)
    api(nvaLibs.json)
    api(project(':data-report-commons'))
    implementation(nvaCatalog.aws.sdk2.sdk.core)
    implementation(nvaCatalog.jackson.databind)
    implementation(nvaCatalog.jena.arq)
    implementation(nvaCatalog.jena.core)
    implementation(nvaCatalog.log4j.core)
    implementation(nvaLibs.s3)
    runtimeOnly(nvaCatalog.jackson.core)
    runtimeOnly(nvaCatalog.log4j.api)
    runtimeOnly(nvaCatalog.log4j.slf4j.impl)
    testImplementation(nvaCatalog.junit.jupiter.api)
    testImplementation(nvaCatalog.junit.jupiter.params)
    testImplementation(nvaCatalog.mockito.core)
    testImplementation(nvaLibs.testutils)
    testImplementation(project(':testing-utils'))
    testRuntimeOnly(libs.jena.fuseki)
    testRuntimeOnly(libs.jena.fuseki.server)
    testRuntimeOnly(nvaCatalog.junit.jupiter.engine)
}

test {
    environment("QUERY_PATH", "gsp/sparql")
    environment("API_HOST", "https://example.org")
    environment("EXPORT_BUCKET", "s3://exportBucket")
}
