openapi: 3.0.3
info:
  title: NVA data report API
  version: 1.0.0
  description: API for generating simple data reports.
x-amazon-apigateway-request-validators:
  validate_body:
    validateRequestBody: true
    validateRequestParameters: false
paths:
  /{type}:
    get:
      description: Get report for a given report type, supporting text/csv download according to <https://www.rfc-editor.org/rfc/rfc4180>
      summary: Get report
      operationId: getDataReport
      parameters:
        - in: path
          name: type
          description: The identifier of the report type
          required: true
          schema:
            type: string
            enum:
              - affiliation
              - contributor
              - funding
              - identifier
              - publication
        - in: query
          name: after
          description: The starting date of the report
          required: false
          schema:
            type: string
            format: date
          example: 2020-01-01
        - in: query
          name: before
          description: The up-to-and-including end date of the report
          required: false
          schema:
            type: string
            format: date
          example: 2022-12-31
        - in: query
          name: limit
          description: The number of results per page
          required: false
          schema:
            type: integer
          example: 10
        - in: query
          name: offset
          description: The number of results to skip
          required: false
          schema:
            type: integer
          example: 10
      security:
        - CognitoUserPool: [
          'https://api.nva.unit.no/scopes/backend',
          'https://api.nva.unit.no/scopes/frontend',
          'aws.cognito.signin.user.admin',
          'https://api.nva.unit.no/scopes/third-party/reporting-read'
        ]
      x-amazon-apigateway-integration:
        uri:
          Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${FetchDataReportHandler.Arn}:live/invocations
        responses: { }
        httpMethod: POST
        type: AWS_PROXY
      responses:
        '200':
          description: "OK"
          content:
            text/plain:
              schema:
                type: string
                format: string
              example: |
                | ------------- | ------------- | ---------------- | 
                | columnHeader1 | columnHeader2 | columnHeaders... |
                | ------------- | ------------- | ---------------- |
                | row1 value1   | row1 value2   | row1 value3      |
                | row2 value1   | row2 value2   | row2 value3      |
                | row... value1 | row... value2 | row... value3    |
                | ------------- | ------------- | ---------------- |
            text/csv:
              schema:
                $ref: "#/components/schemas/CsvResponse"
              example: |
                columnHeader1,columnHeader2,columnHeaders...
                "row1 value1","row1 value2","row1 value3"
                "row2 value1","row2 value2","row2 value3"
                "row... value1","row... value2""row... value3"
        '404':
          description: "Report not found"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Problem"
        '500':
          description: "Internal Server Error"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Problem"
  /institution/nvi-approval/{reportingYear}:
    get:
      description: Get institution report for nvi for given reporting year. Supporting text/csv download according to <https://www.rfc-editor.org/rfc/rfc4180>, application/vnd.ms-excel and application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.
      summary: Get nvi institution report
      operationId: getReportNviInstitution
      security:
        - CognitoUserPool: [
          'https://api.nva.unit.no/scopes/backend',
          'https://api.nva.unit.no/scopes/frontend',
          'aws.cognito.signin.user.admin'
        ]
      x-amazon-apigateway-integration:
        uri:
          Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${FetchNviInstitutionReportPresignerHandler.Arn}:live/invocations
        responses: { }
        httpMethod: POST
        type: AWS_PROXY
      parameters:
        - in: path
          name: reportingYear
          description: The reporting year the institutions nvi report should be generated for
          required: true
          schema:
            type: string
      responses:
        '200':
          description: "OK"
          content:
            application/vnd.ms-excel:
              schema:
                $ref: "#/components/schemas/BinaryResponse"
            application/vnd.openxmlformats-officedocument.spreadsheetml.sheet:
              schema:
                $ref: "#/components/schemas/BinaryResponse"
        '401':
          description: "Unauthorized"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Problem"
        '500':
          description: "Internal Server Error"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Problem"
components:
  schemas:
    CsvResponse:
      type: string
    BinaryResponse:
      type: string
      format: binary
    Problem:
      type: object
      description: NVA error reporting object
      required:
        - title
        - detail
        - status
      properties:
        title:
          type: string
          description: Human-readable description of the error status
        detail:
          type: string
          description: A more detailed error message describing the error and potential mitigations
        status:
          type: integer
          description: The HTTP status code associated with the problem
        requestId:
          type: string
          description: Identifier of the request causing the problem
        instance:
          type: string
          description: The requested path associated with the error
        type:
          type: string
          description: A URI describing the error and mitigations, in generic cases, this is about:blank
  securitySchemes:
    CognitoUserPool:
      type: apiKey
      name: Authorization
      in: header
      x-amazon-apigateway-authtype: cognito_user_pools
      x-amazon-apigateway-authorizer:
        type: cognito_user_pools
        providerARNs:
          - Ref: CognitoAuthorizerArn
          - Ref: ExternalCognitoAuthorizerArn
