plugins {
    id 'nva.data.report.api.java-conventions'
}

dependencies {
    api(libs.commons.csv)
    api(nvaCatalog.aws.sdk2.eventbridge)
    api(nvaCatalog.jackson.annotations)
    api(nvaCatalog.jackson.databind)
    api(nvaCatalog.jena.core)
    api(nvaLibs.json)
    api(nvaLibs.s3)
    api(project(':data-report-commons'))
    implementation(libs.commons.io)
    implementation(nvaCatalog.jackson.core)
    implementation(nvaLibs.core)
    implementation(nvaLibs.testutils)
    runtimeOnly(libs.jena.fuseki)
}
